version: 2
jobs:
  Python_3.5:
    docker:
      - image: circleci/python:3.5.4 # https://github.com/CircleCI-Public/circleci-dockerfiles/tree/master/python/images/3.5.4
    steps:
      - checkout
      - run: sudo pip install -r requirements.txt
      - run: pytest

workflows:
  version: 2
  build:
    jobs:
      - Python_3.5
